# NumPy Cơ Bản

Thư viện tính toán số học — nền tảng của Pandas, scikit-learn. Dùng khi cần xử lý mảng số, tính thống kê, hoặc thao tác ma trận nhanh hơn Python thuần.

In [1]:
import numpy as np

## 1. ndarray, shape, dtype

- **`np.array()`** — tạo array từ list. Tất cả phần tử cùng kiểu (`dtype`).
- **`.shape`** — tuple `(rows, cols)` thể hiện kích thước array.
- **`.dtype`** — kiểu dữ liệu của phần tử (`int64`, `float64`, ...).
- **`.reshape(r, c)`** — đổi shape, dùng `-1` để tự tính một chiều.
- **`.astype()`** — ép kiểu dữ liệu.

> Khác list: array có shape cố định và dtype đồng nhất — nhanh hơn nhiều khi tính toán số học.

In [2]:
# np.array() — tạo array
a = np.array([1, 2, 3, 4, 5])
m = np.array([[1, 2, 3], [4, 5, 6]])

print(a)        # [1 2 3 4 5]
print(m)        # [[1 2 3] [4 5 6]]

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [4]:
# .shape và .dtype
print(m.shape)   # (2, 3) — 2 hàng, 3 cột
print(m.ndim)    # 2 — số chiều
print(m.size)    # 6 — tổng phần tử
print(m.dtype)   # int64
print(type(m))

(2, 3)
2
6
int64
<class 'numpy.ndarray'>


In [ ]:
# .reshape() — đổi shape
a = np.arange(12)          # [0, 1, ..., 11]
print(a.reshape(3, 4))     # 3 hàng x 4 cột
print(a.reshape(3, -1))    # -1: tự tính = 4 cột

In [ ]:
# .astype() — ép kiểu
a = np.array([1, 2, 3])
print(a.dtype)             # int64
print(a.astype(float))     # [1. 2. 3.] — float64

### Luyện tập

- **Bài 1:** Tạo array chứa điểm thi của 5 học sinh `[7.5, 8.0, 6.5, 9.0, 5.5]`. In ra shape, dtype, và ép kiểu về `int`.
- **Bài 2:** Tạo array `np.arange(1, 13)` rồi reshape thành ma trận 3 hàng, tự tính cột. In kết quả.

In [ ]:
# Viết code của bạn ở đây


## 2. Indexing, Slicing, Boolean Masking

- **Indexing** — truy cập phần tử: `a[i]` (1D), `m[row, col]` (2D). Index âm đếm từ cuối.
- **Slicing** — cắt mảng: `a[start:stop:step]`, `m[:, 1]` (toàn bộ cột 1).
- **Boolean masking** — lọc theo điều kiện: `a[a > 5]` trả về array các phần tử thỏa điều kiện.

> Dùng `&` (AND) và `|` (OR) khi kết hợp nhiều điều kiện — **phải có ngoặc** bao mỗi điều kiện.

In [ ]:
# Indexing 1D và 2D
a = np.array([10, 20, 30, 40, 50])
print(a[0])    # 10
print(a[-1])   # 50

m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m[1, 2])    # 6 — hàng 1, cột 2
print(m[0, :])    # [1 2 3] — toàn bộ hàng 0
print(m[:, 1])    # [2 5 8] — toàn bộ cột 1

In [ ]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m[0]) # Hàng 1 
print(m[:, 2])
print(m[:][2])
print(m[1, 2])
print(m[1][2])

[1 2 3]
[3 6 9]
[7 8 9]
6
6


In [ ]:
# Slicing
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])    # [20 30 40]
print(a[::2])    # [10 30 50] — bước 2

m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m[1:, 1:]) # [[5 6] [8 9]] — sub-matrix

In [ ]:
# Boolean masking
diem = np.array([4.0, 7.5, 5.0, 8.5, 3.5, 6.0])

print(diem[diem >= 5.0])              # lọc đạt: [7.5 5.  8.5 6. ]
print(diem[(diem >= 5.0) & (diem < 8.0)])  # đạt nhưng chưa giỏi: [7.5 5.  6. ]

### Luyện tập

- **Bài 1:** Cho array doanh thu tháng `[120, 85, 200, 95, 310, 150]`. Lọc ra các tháng có doanh thu trên 100 triệu.
- **Bài 2:** Tạo ma trận 4x4 từ `np.arange(16).reshape(4,4)`. Lấy sub-matrix 2x2 ở góc dưới phải.

In [ ]:
# Viết code của bạn ở đây


## 3. Thống kê: mean, std, percentile, where

- **`np.mean(a)`** — trung bình. Thêm `axis=0` tính theo cột, `axis=1` theo hàng.
- **`np.std(a)`** — độ lệch chuẩn population. `ddof=1` để tính sample std.
- **`np.percentile(a, q)`** — phân vị thứ q. `q=25/50/75` tương ứng Q1/Q2/Q3.
- **`np.where(cond, x, y)`** — trả về `x` nếu điều kiện đúng, `y` nếu sai.

> `np.std()` mặc định chia N (population). Dùng `ddof=1` khi dữ liệu là mẫu (sample).

In [ ]:
# mean và std
diem = np.array([6.0, 7.5, 8.0, 5.5, 9.0, 4.5, 7.0, 8.5])

print(np.mean(diem))       # 7.0
print(np.median(diem))     # 7.25 (giữa 7.0 và 7.5)
print(np.std(diem))        # population std
print(np.std(diem, ddof=1))# sample std

7.0
7.25
1.4577379737113252
1.558387444947959


In [20]:
# percentile — phân vị
diem = np.array([6.0, 7.5, 8.0, 5.5, 9.0, 4.5, 7.0, 8.5])

Q1 = np.percentile(diem, 25)
Q3 = np.percentile(diem, 75)
IQR = Q3 - Q1

print(f"Q1={Q1}, Q3={Q3}, IQR={IQR}")

# Lọc outlier theo IQR
khong_outlier = diem[(diem >= Q1 - 1.5*IQR) & (diem <= Q3 + 1.5*IQR)]
print(khong_outlier)

Q1=5.875, Q3=8.125, IQR=2.25
[6.  7.5 8.  5.5 9.  4.5 7.  8.5]


In [21]:
# np.where — gán nhãn theo điều kiện
diem = np.array([6.0, 7.5, 8.0, 5.5, 9.0, 4.5])

ket_qua = np.where(diem >= 5.0, "Đạt", "Rớt")
print(ket_qua)  # ['Đạt' 'Đạt' 'Đạt' 'Đạt' 'Đạt' 'Rớt']

# Thay giá trị: giữ điểm nếu đạt, thay 0 nếu rớt
print(np.where(diem >= 5.0, diem, 0))

['Đạt' 'Đạt' 'Đạt' 'Đạt' 'Đạt' 'Rớt']
[6.  7.5 8.  5.5 9.  0. ]


### Luyện tập

- **Bài 1:** Tạo 50 điểm ngẫu nhiên `np.random.randint(0, 11, 50)`. Tính mean, std, Q1, Q3. Đếm số học sinh đạt (>= 5).
- **Bài 2:** Dùng `np.where` để gán xếp loại: `>= 8.5` → `"Giỏi"`, `>= 5` → `"Đạt"`, còn lại → `"Yếu"`. *(Gợi ý: lồng 2 `np.where`)*

In [ ]:
# Viết code của bạn ở đây
a = np.random.randint(0, 11, 50) #low, high, size

array([10,  3,  3,  2, 10,  7,  0,  4,  0,  9,  3,  0, 10,  2, 10, 10,  3,
        4,  0,  6,  7,  8,  7,  0,  3,  1,  5, 10, 10,  5,  4,  0, 10,  5,
       10,  5,  0,  0,  7,  5,  9,  7,  3,  3,  6, 10,  9,  6,  6, 10],
      dtype=int32)

## 4. Broadcasting

NumPy tự động "kéo giãn" array nhỏ hơn để phù hợp với array lớn hơn — không cần viết vòng lặp.

**Quy tắc tương thích:** hai chiều tương thích khi bằng nhau, hoặc một trong hai bằng 1.

- **Scalar + array** — áp dụng scalar lên mọi phần tử.
- **1D + 2D** — array 1D được broadcast theo chiều phù hợp.

> Broadcasting giúp normalize, chuẩn hóa dữ liệu không cần loop — rất phổ biến trong thực tế.

In [ ]:
# Scalar + array
a = np.array([1, 2, 3, 4, 5])
print(a + 10)    # [11 12 13 14 15]
print(a * 2)     # [2  4  6  8 10]
print(a ** 2)    # [1  4  9 16 25]

In [ ]:
# 1D broadcast trên 2D — trừ mean từng cột
data = np.array([[80, 70, 90],
                 [60, 85, 75],
                 [90, 65, 80]], dtype=float)

col_mean = np.mean(data, axis=0)   # [76.67, 73.33, 81.67] — shape (3,)
centered = data - col_mean         # broadcast: trừ mean từng cột
print(col_mean)
print(centered)

In [ ]:
# Normalize toàn bộ array về [0, 1]
data = np.array([10, 20, 30, 40, 50], dtype=float)

normalized = (data - data.min()) / (data.max() - data.min())
print(normalized)  # [0.   0.25 0.5  0.75 1.  ]

### Luyện tập

- **Bài 1:** Cho bảng điểm 3 môn của 4 học sinh (ma trận 4x3). Tính điểm trung bình từng môn (theo cột), rồi trừ mean để center dữ liệu.
- **Bài 2:** Normalize từng cột của bảng điểm trên về [0, 1]. *(Gợi ý: tính min/max theo `axis=0` rồi dùng broadcasting)*

In [ ]:
# Viết code của bạn ở đây
